- name: install i3
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - i3-wm
  - i3blocks
  - i3lock
  - i3status
- name: ensure awesomewm configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/i3 state=directory recurse=yes
- name: copy i3 config
  copy: src=templates/i3/config dest={{ ansible_env.HOME }}/.config/i3/config

- name: install dunst (notifications daemon)
  pacman: package=dunst state=present
  become: yes
- name: ensure dunst configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/dunst state=directory recurse=yes
- name: copy dunst config
  copy: src=templates/dunstrc dest={{ ansible_env.HOME }}/.config/dunst/dunstrc
  notify: kill dunst
