---
- include: xorg_packages.yml

- include: lightdm.yml

- name: configure xkb input languages
  copy: src=templates/xorg/10-xkb.conf dest=/etc/X11/xorg.conf.d/10-xkb.conf
  become: yes

- name: install awesomewm
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - awesome
  - vicious
  - alsa-utils  # volume widget
  - wireless_tools  # wi-fi widget
- name: ensure awesomewm configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/awesome state=directory recurse=yes
- name: copy awesomewm config
  copy: src=templates/awesome/rc.lua dest={{ ansible_env.HOME }}/.config/awesome/rc.lua
- name: copy awesomewm wallpaper
  copy: src=templates/awesome/background.jpg dest={{ ansible_env.HOME }}/.config/awesome/background.jpg

- include: i3.yml

- name: install terminal emulator
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - rxvt-unicode
  - urxvt-perls
- name: configure terminal emulator
  copy: src=templates/Xdefaults dest={{ ansible_env.HOME }}/.Xdefaults

- include: multimedia.yml

- include: office.yml

- include: p2p.yml

- name: install browsers
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - firefox
  - firefox-extension-ghostery
  - firefox-adblock-plus
  - firefox-noscript
  - chromium

- name: install fonts
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - ttf-anonymous-pro
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-droid
  - ttf-freefont
  - ttf-inconsolata
  - ttf-liberation
  - ttf-ubuntu-font-family
  - ttf-symbola

- name: install Intel AMT management software
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - remmina
  - libvncserver
