---
- include: xorg_packages.yml

- include: lightdm.yml

- name: configure xkb input languages
  copy: src=templates/xorg/10-xkb.conf dest=/etc/X11/xorg.conf.d/10-xkb.conf
  become: yes

- include: i3.yml

- name: install terminal emulator
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - rxvt-unicode
  - urxvt-perls
- name: configure terminal emulator
  copy: src=templates/Xdefaults dest={{ ansible_env.HOME }}/.Xdefaults

- include: multimedia.yml

- include: office.yml

- include: p2p.yml

- name: install browsers
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - firefox
  - firefox-extension-ghostery
  - firefox-adblock-plus
  - firefox-noscript
  - chromium

- name: install fonts
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - ttf-anonymous-pro
  - ttf-dejavu
  - ttf-droid
  - ttf-freefont
  - ttf-inconsolata
  - ttf-liberation
  - ttf-ubuntu-font-family
  - ttf-symbola

- name: set default apps
  copy: src=templates/mimeapps.list dest={{ ansible_env.HOME }}/.config/mimeapps.list

- name: install Intel AMT management software
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - remmina
  - libvncserver
