---
- include: xorg_packages.yml

- include: lightdm.yml

- name: configure xkb input languages
  copy: src=templates/xorg/10-xkb.conf dest=/etc/X11/xorg.conf.d/10-xkb.conf
  become: yes

- include: i3.yml

- name: install terminal emulators
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - rxvt-unicode
  - urxvt-perls
  - alacritty
  - alacritty-terminfo
- name: configure terminal emulator urxvt
  copy: src=templates/Xdefaults dest={{ ansible_env.HOME }}/.Xdefaults
- name: configure terminal emulator alacritty
  copy: src=templates/alacritty/alacritty.yml dest={{ ansible_env.HOME }}/.config/alacritty/alacritty.yml
- name: copy alacritty wrapper script
  copy: src=templates/term dest=/usr/bin/term mode=0555 owner=root group=root
  become: yes

- include: multimedia.yml

- include: office.yml

- include: p2p.yml

- name: install browsers
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - firefox
  - firefox-adblock-plus
  - firefox-noscript
  - chromium

- name: install fonts
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - ttf-anonymous-pro
  - ttf-dejavu
  - ttf-droid
  - ttf-freefont
  - ttf-inconsolata
  - ttf-liberation
  - ttf-ubuntu-font-family
  - ttf-symbola

- name: set default apps
  copy: src=templates/mimeapps.list dest={{ ansible_env.HOME }}/.config/mimeapps.list

- name: install Intel AMT management software
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - remmina
  - libvncserver

- name: install syncthing
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - syncthing
  - syncthing-gtk
- name: enable syncthing
  systemd: name=syncthing@{{ ansible_user_id }} state=started enabled=yes
  become: yes
- name: copy syncthing-gtk config
  copy: src=templates/syncthing-gtk/config.json dest={{ ansible_env.HOME }}/.config/syncthing-gtk/config.json
