---
- include: xorg_packages.yml

- name: configure xkb input languages
  copy: src=templates/xorg/10-xkb.conf dest=/etc/X11/xorg.conf.d/10-xkb.conf
  become: yes

- include: i3.yml
- include: sway.yml

- name: install terminal emulators
  pacman:
    state: present
    package:
    - alacritty
    - alacritty-terminfo
  become: yes
- name: configure terminal emulator alacritty
  copy: src=templates/alacritty/alacritty.yml dest={{ ansible_env.HOME }}/.config/alacritty/alacritty.yml
- name: copy alacritty wrapper script
  copy: src=templates/term dest=/usr/bin/term mode=0555 owner=root group=root
  become: yes

- include: multimedia.yml

- include: office.yml

- include: p2p.yml

- name: install browsers
  pacman:
    state:  present
    package:
    - firefox
    - firefox-adblock-plus
    - firefox-noscript
    - chromium
  become: yes

- name: install fonts
  pacman:
    state: present
    package:
    - ttf-anonymous-pro
    - ttf-dejavu
    - ttf-droid
    - gnu-free-fonts
    - ttf-inconsolata
    - ttf-liberation
    - ttf-ubuntu-font-family
    - ttf-symbola
  become: yes

- name: set default apps
  copy: src=templates/mimeapps.list dest={{ ansible_env.HOME }}/.config/mimeapps.list

- name: install Intel AMT management software
  pacman:
    state: present
    package:
    - remmina
    - libvncserver
  become: yes
