- name: install pulseaudio
  pacman:
    state: installed
    package:
    - pulseaudio
    - pavucontrol
    - pamixer
  become: yes

- name: install audio packages
  pacman:
    state: installed
    package:
    - deadbeef
    - ffmpeg
    - libvorbis
    - libmad
    - flac
    - vlc
  become: yes

- name: install imaging packages
  pacman:
    state: installed
    package:
    - sxiv
    - imagemagick
    - gimp
    - scrot
  become: yes
