- name: install pulseaudio
  pacman: package={{ item }} state=installed
  become: yes
  with_items:
  - pulseaudio
  - pavucontrol
  - pamixer

- name: install audio packages
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - deadbeef
  - ffmpeg
  - libvorbis
  - libmad
  - flac
  - vlc

- name: install imaging packages
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - sxiv
  - imagemagick
  - gimp
