- name: install bluetooth
  pacman:
    state: installed
    package: bluez
  become: yes
- name: auto enable bluetooth controller
  lineinfile: >
    dest=/etc/bluetooth/main.conf
    line="AutoEnable=true"
    regexp="AutoEnable="
  become: yes
- name: enable and start bluetooth service
  service: name=bluetooth state=started enabled=yes
  become: yes

- name: install pulseaudio
  pacman:
    state: installed
    package:
    - pulseaudio
    - pavucontrol
    - pamixer
    - pulseaudio-modules-bt-git
  become: yes
- name: enable pulseaudio module switch-on-connect for bluetooth devices
  lineinfile: >
    dest=/etc/pulse/default.pa
    line="load-module module-switch-on-connect"
  become: yes
- name: enable and start pulseaudio service
  systemd: name=pulseaudio scope=user state=started enabled=yes

- name: install audio packages
  pacman:
    state: installed
    package:
    - deadbeef
    - ffmpeg
    - libvorbis
    - libmad
    - flac
    - vlc
  become: yes

- name: install imaging packages
  pacman:
    state: installed
    package:
    - sxiv
    - imagemagick
    - gimp
    - scrot
  become: yes
