- name: install bluetooth
  pacman:
    state: installed
    package: bluez
  become: yes
- name: auto enable bluetooth controller
  lineinfile: >
    dest=/etc/bluetooth/main.conf
    line="AutoEnable=true"
    regexp="AutoEnable="
  become: yes
- name: enable and start bluetooth service
  service: name=bluetooth state=started enabled=yes
  become: yes

- name: install pipewire
  pacman:
    state: installed
    package:
    - pipewire
    - pipewire-pulse
    - pavucontrol
    - pamixer
  become: yes
- name: install xdg-desktop-portal that uses pipewire
  pacman:
    state: installed
    package:
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
  become: yes

- name: install audio packages
  pacman:
    state: installed
    package:
    - deadbeef
    - ffmpeg
    - libvorbis
    - libmad
    - flac
    - vlc
  become: yes

- name: install imaging packages
  pacman:
    state: installed
    package:
    - sxiv
    - imagemagick
    - gimp
    - scrot
  become: yes
