- name: install pdf reader
  pacman: name=evince state=installed
  become: yes

- name: install libreoffice
  pacman:
    state: installed
    package:
    - libreoffice-fresh
    - libreoffice-fresh-be
    - libreoffice-fresh-ru
  become: yes
