- name: install sway and related packages
  pacman:
    state: present
    package:
    - sway
    - swaybg
    - swaylock
    - swayidle
    - i3status
    - pipewire
    - pipewire-pulse
    - wl-clipboard
    - bemenu  # program launcher
    - ttf-roboto  # font used in sway config (1/2)
    - ttf-roboto-mono  # font used in sway config (2/2)
    - light  # control screen backlight brightness
    - mako  # notifications manager
    - grim  # screenshots
    - slurp  # select part of the screen
  become: yes
- name: ensure sway configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/sway state=directory recurse=yes
- name: copy sway config
  template: src=templates/sway/config dest={{ ansible_env.HOME }}/.config/sway/config
- name: ensure mako configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/mako state=directory recurse=yes
- name: copy mako config
  template: src=templates/mako/config dest={{ ansible_env.HOME }}/.config/mako/config
- name: copy i3status config
  template: src=templates/sway/status.conf dest={{ ansible_env.HOME }}/.config/sway/status.conf
- name: write .Xresources  # will be loaded in sway config
  copy: src=templates/Xresources dest={{ ansible_env.HOME }}/.Xresources
- name: create grim-wrapper
  copy: >
    src=templates/gimp-screenshot
    dest=/usr/bin/gimp-screenshot
    mode=0555
    owner=root
    group=root
  become: yes
- name: copy script sway-move-all-to-current-display.py
  copy: >
    src=templates/sway/sway-move-all-to-current-display.py
    dest={{ ansible_env.HOME }}/.config/sway/sway-move-all-to-current-display.py mode=0555
- name: Add user to group video to make utility light work without sudo
  user: name={{ ansible_user_id }} groups=video append=yes
  become: yes
- name: Autostart sway when logging in on TTY1
  copy: >
    src=templates/sway/sway.fish
    dest={{ ansible_env.HOME }}/.config/fish/conf.d/00-sway.fish
