- name: install sway and related packages
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - sway
  - swaylock
  - swayidle
  - i3status
  - terminus-font  # font used in sway config
  - light  # control screen backlight brightness
  - mako  # notifications manager
- name: ensure sway configuration dir exists
  file: path={{ ansible_env.HOME }}/.config/sway state=directory recurse=yes
- name: copy sway config
  template: src=templates/sway/config dest={{ ansible_env.HOME }}/.config/sway/config
