- name: install xorg
  pacman: package={{ item }} state=present
  become: yes
  with_items:
  - xorg-server
  - xf86-video-intel
  - xf86-input-evdev
  - xf86-input-synaptics
  - mesa
- name: install xorg-apps
  pacman: package={{ item }} state=present
  with_items:  # also known as xorg-apps metapackage
  - xorg-bdftopcf
  - xorg-iceauth
  - xorg-luit
  - xorg-mkfontdir
  - xorg-mkfontscale
  - xorg-sessreg
  - xorg-setxkbmap
  - xorg-smproxy
  - xorg-x11perf
  - xorg-xauth
  - xorg-xbacklight
  - xorg-xcmsdb
  - xorg-xcursorgen
  - xorg-xdpyinfo
  - xorg-xdriinfo
  - xorg-xev
  - xorg-xgamma
  - xorg-xhost
  - xorg-xinput
  - xorg-xkbcomp
  - xorg-xkbevd
  - xorg-xkbutils
  - xorg-xkill
  - xorg-xlsatoms
  - xorg-xlsclients
  - xorg-xmodmap
  - xorg-xpr
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xrefresh
  - xorg-xset
  - xorg-xsetroot
  - xorg-xvinfo
  - xorg-xwd
  - xorg-xwininfo
  - xorg-xwud

