---
- name: "install packages"
  pacman:
    state: installed
    package:
    - gnupg
    - openssh
    - pass
  become: yes

- name: "create .gnupg"
  file: path=/home/{{ ansible_user_id }}/.gnupg state=directory mode=0700
- name: add arch devs to gpg.conf
  lineinfile: dest={{ ansible_env.HOME }}/.gnupg/gpg.conf line="keyring /etc/pacman.d/gnupg/pubring.gpg" create=yes
- name: "enable ssh support in gpg agent"
  copy: >
    src=templates/home/user/.gnupg/gpg-agent.conf
    dest={{ ansible_env.HOME }}/.gnupg/gpg-agent.conf

- name: "copy fish condiguration preset for ssh-agent"
  copy: >
    src=templates/ssh-agent.fish
    dest={{ ansible_env.HOME }}/.config/fish/conf.d/10-ssh-agent.fish

- name: "ensure .ssh exists"
  file: path={{ ansible_env.HOME }}/.ssh state=directory mode=0700
- name: configure openssh to update startup tty before calling gpg-agent (relies on GPG_TTY from ssh-agent.fish)
  lineinfile: >
    dest={{ ansible_env.HOME }}/.ssh/config
    line='Match host * exec "gpg-connect-agent UPDATESTARTUPTTY /bye"'

- name: install yubikey tools
  pacman:
    state: installed
    package:
    - yubikey-manager
    - yubikey-personalization
    - yubikey-personalization-gui
  become: yes
