---
- name: "install packages"
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - gnupg
    - openssh
    - pass

- name: "create .gnupg"
  file: path=/home/{{ ansible_user_id }}/.gnupg state=directory mode=0700
- name: add arch devs to gpg.conf
  lineinfile: dest={{ ansible_env.HOME }}/.gnupg/gpg.conf line="keyring /etc/pacman.d/gnupg/pubring.gpg"

- name: "ensure .zshrc.d exists"
  file: path=/home/{{ ansible_user_id }}/.zshrc.d state=directory
- name: "copy zsh condiguration preset for ssh-agent"
  copy: >
    src=templates/home/user/.zshrc.d/00-ssh-agent.sh
    dest=/home/{{ ansible_user_id }}/.zshrc.d/00-ssh-agent.sh

- name: ensure .config/systemd/user exists
  file: path={{ ansible_env.HOME }}/.config/systemd/user state=directory recurse=yes
- name: "copy ssh-agent service"
  copy: >
    src=templates/home/user/.config/systemd/user/ssh-agent.service
    dest=/home/{{ ansible_user_id }}/.config/systemd/user/ssh-agent.service
- name: "start ssh-agent service"
  systemd: name=ssh-agent user=yes state=started enabled=yes

- name: install yubikey tools
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - yubikey-manager
    - yubikey-personalization
    - yubikey-personalization-gui
