---
- name: "install packages"
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - gnupg
    - openssh
    - pass

- name: "create .gnupg"
  file: path=/home/{{ ansible_user_id }}/.gnupg state=directory mode=0700
- name: add arch devs to gpg.conf
  lineinfile: dest={{ ansible_env.HOME }}/.gnupg/gpg.conf line="keyring /etc/pacman.d/gnupg/pubring.gpg" create=yes
- name: "enable ssh support in gpg agent"
  copy: >
    src=templates/home/user/.gnupg/gpg-agent.conf
    dest={{ ansible_env.HOME }}/.gnupg/gpg-agent.conf

- name: "ensure .zshrc.d exists"
  file: path=/home/{{ ansible_user_id }}/.zshrc.d state=directory
- name: "copy zsh condiguration preset for ssh-agent"
  copy: >
    src=templates/home/user/.zshrc.d/00-ssh-agent.sh
    dest=/home/{{ ansible_user_id }}/.zshrc.d/00-ssh-agent.sh

- name: "start gpg-agent service"
  systemd: name=gpg-agent user=yes state=started enabled=yes

- name: install yubikey tools
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - yubikey-manager
    - yubikey-personalization
    - yubikey-personalization-gui
