---
- name: "install grub"
  pacman: name=grub state=installed
  become: yes
- name: "skip filesystem balance on reboot"
  lineinfile: >
    dest=/etc/default/grub
    line='GRUB_CMDLINE_LINUX="rootflags=subvol=@,skip_balance"'
    regexp="GRUB_CMDLINE_LINUX="
  become: yes

- name: "install ntp"
  pacman: name=ntp state=installed
  become: yes
- name: "enable ntp"
  systemd: name=ntpd enabled=yes state=started
  become: yes

- name: "install btrfs progs"
  pacman: name=btrfs-progs state=installed
  become: yes

- name:  install netctl and related tools
  pacman:
    state: installed
    package:
    - netctl
    - dialog  # used by wifi-menu
    - wpa_supplicant
    - wpa_actiond  # used by netctl-auto
    - ifplugd  # used by netctl-ifplugd
  become: yes

- name: enable netctl-auto
  systemd: name=netctl-auto@{{ wlan0 }} enabled=yes state=started
  become: yes
  when: wlan0 != 'none'

- name: install openvpn and related tools
  pacman:
    state: installed
    package:
    - openvpn
    - openresolv
  become: yes
- name: copy update-resolv-conf
  copy: >
    src=templates/openvpn/update-resolv-conf
    dest=/usr/bin/update-resolv-conf
    mode=ugo=rx
    owner=root
  become: yes

- name: install 3g modem software
  pacman: package=wvdial state=installed
  become: yes

- name: install network-related utils
  pacman: name=net-tools state=installed
  become: yes

- name: "copy disable-acpi-wakeup service"
  copy: >
    src=templates/disable-acpi-wakeup.service
    dest=/usr/lib/systemd/system/disable-acpi-wakeup.service
    owner=root
    group=root
  become: yes
- name: "start disable-acpi-wakeup service"
  systemd: name=disable-acpi-wakeup state=started enabled=yes daemon_reload=yes
  become: yes
