---
- name: Install packages
  pacman:
    state: installed
    package:
    - kubectl
    - kubectx
    - minikube
    - libvirt  # will be used by minikube to start kvm2 machines
    - ebtables  # firewall used by libvirt
    - dnsmasq  # firewall used by libvirt
  become: yes

- name: Start libvirtd which is used by minikube
  systemd: service=libvirtd state=started
  become: yes

- name: Add the current user to group libvirtd so they can run minikube without root
  user: name={{ ansible_user_id }} groups=libvirt append=yes
  become: yes
