---
- name: "install packages"
  pacman:
    state: installed
    package:
    - emacs
    - cask  # dependency management - installed from AUR
    - flake8
    - python2-flake8
    - discount  # previously known as markdown, also provides markdown binary
    - plantuml
  become: yes

- name: "copy .emacs"
  template: >
    src=templates/.emacs
    dest=/home/{{ ansible_user_id }}/.emacs
- name: "ensure .emacs.d exists"
  file: path=/home/{{ ansible_user_id }}/.emacs.d state=directory
- name: "copy .emacs.d/*.el"
  copy: >
    src=templates/.emacs.d/{{ item }}
    dest=/home/{{ ansible_user_id }}/.emacs.d/{{ item }}
  with_items:
    - Cask
    - startup.el
    - builtin.el
    - external.el

- name: "cask install"
  shell: "cask install --verbose"
  args:
    chdir: "/home/{{ ansible_user_id }}/.emacs.d"

- name: "copy emacsclient shortcut"
  copy: >
    src=templates/e
    dest=/usr/bin/e
    mode=0555
    owner=root
    group=root
  become: yes

- name: ensure .zshrc.d exists
  file: path={{ ansible_env.HOME }}/.zshrc.d state=directory
- name: set EDITOR=e -t
  copy: content='export EDITOR="emacs -nw -Q"\n' dest={{ ansible_env.HOME }}/.zshrc.d/50-editor-e.sh
