---
- name: "install packages"
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - emacs
    - flake8
    - python2-flake8
    - markdown

- name: "copy .emacs"
  template: >
    src=templates/.emacs
    dest=/home/{{ ansible_user_id }}/.emacs
- name: "ensure .emacs.d exists"
  file: path=/home/{{ ansible_user_id }}/.emacs.d state=directory
- name: "copy .emacs.d/*.el"
  copy: >
    src=templates/.emacs.d/{{ item }}
    dest=/home/{{ ansible_user_id }}/.emacs.d/{{ item }}
  with_items:
    - startup.el
    - ui.el
    - packaging.el
    - editing.el
    - org.el

- name: "copy user el-get recipes"
  copy: >
    src=templates/.emacs.d/el-get-user/
    dest=/home/{{ ansible_user_id }}/.emacs.d/el-get-user/

- name: "copy daemon service"
  template: >
    src=templates/.config/systemd/user/emacs.service
    dest=/home/{{ ansible_user_id }}/.config/systemd/user/emacs.service
- name: "start daemon service"
  systemd: name=emacs user=yes state=started enabled=yes

- name: "copy emacsclient shortcut"
  copy: >
    src=templates/e
    dest=/usr/bin/e
    mode=0555
    owner=root
    group=root
  become: yes

- name: ensure .zshrc.d exists
  file: path={{ ansible_env.HOME }}/.zshrc.d state=directory
- name: set EDITOR=e -t
  copy: content='export EDITOR="e -t"\n' dest={{ ansible_env.HOME }}/.zshrc.d/50-editor-e.sh
