---
- name: ensure ~/projects exists
  file: path={{ ansible_env.HOME }}/projects state=directory

- include: scm.yml

- name: install docker
  pacman: package={{ item }} state=installed
  become: yes
  with_items:
  - docker
  - docker-compose
- name: start docker daemon
  systemd: name=docker enabled=yes state=started
  become: yes

- include: nix.yml

- include: python.yml

- include: rust.yml
