---
- name: ensure ~/projects exists
  file: path={{ ansible_env.HOME }}/projects state=directory

- include: scm.yml

- name: install docker
  pacman:
    state: installed
    package:
    - docker
    - docker-compose
  become: yes
- name: start docker daemon
  systemd: name=docker enabled=yes state=started
  become: yes

- include: nix.yml

- include: python.yml

- include: rust.yml
