- name: install python and related packages
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - python
  - python2
  - pypy
  - pypy3
  - ipython
  - ipython2
  - python-virtualenv
  - python-virtualenvwrapper
  - flake8
  - python2-flake8

- name: ensure .zshrc.d exists
  file: path={{ ansible_env.HOME }}/.zshrc.d state=directory
- name: source virtualenvwrapper in zshrc
  copy: >
    content="#!/usr/bin/bash\nsource /usr/bin/virtualenvwrapper.sh\n"
    dest={{ ansible_env.HOME }}/.zshrc.d/50-virtualenvwrapper.sh

- name: install jupyter notebook
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
  - jupyter-notebook
