- name: install python and related packages
  pacman:
    state: installed
    package:
    - python
    - python2
    - pypy
    - pypy3
    - ipython
    - ipython2
    - python-virtualenv
    - python-virtualenvwrapper
    - flake8
    - python2-flake8
    - python-poetry
  become: yes

- name: install datascience tools
  pacman:
    state: installed
    package:
    - jupyter-notebook
    - jupyter-nbconvert
    - python-pandas
    - python-seaborn
    - python-scikit-learn
  become: yes
