---
- include_vars: boxes.yml

- name: "install packages"
  pacman: name={{ item }} state=installed
  become: yes
  with_items:
    - isync
    - mu-git

- name: "copy mbsyncrc"
  template: >
    src=templates/.mbsyncrc
    dest=/home/{{ ansible_user_id }}/.mbsyncrc
    mode=u=r

- include: bootstrap_mailbox.yml
  with_items: "{{ boxes }}"

- include: bootstrap_mu.yml

- name: "copy mbsync service"
  copy: >
    src=templates/.config/systemd/user/mbsync.service
    dest=/home/{{ ansible_user_id }}/.config/systemd/user/mbsync.service
  when: boxes
- name: "start mbsync service"
  systemd: name=mbsync.service user=yes state=started enabled=yes
  when: boxes

- name: "copy mbsync timer"
  copy: >
    src=templates/.config/systemd/user/mbsync.timer
    dest=/home/{{ ansible_user_id }}/.config/systemd/user/mbsync.timer
  when: boxes
- name: "start mbsync timer"
  systemd: name=mbsync.timer user=yes state=started enabled=yes
  when: boxes

- name: "ensure .emacs.d exists"
  file: path=/home/{{ ansible_user_id }}/.emacs.d state=directory
- name: "copy emacs' mail.el"
  template: >
    src=templates/.emacs.d/mail.el
    dest=/home/{{ ansible_user_id }}/.emacs.d/mail.el
