---
- name: install sudo
  pacman: package=sudo
  become: yes
- name: add wheel group to sudoers
  copy: src=templates/sudoers/10-wheel dest=/etc/sudoers.d/10-wheel
  become: yes

- name: install zsh
  pacman: package=zsh state=present
  become: yes
- name: create .zshrc.d
  file: path={{ ansible_env.HOME }}/.zshrc.d state=directory
- name: copy .zshrc
  template: src=templates/zshrc dest={{ ansible_env.HOME }}/.zshrc
- name: set zsh as a default shell for {{ ansible_user_id }}
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes

- name: install resource monitors
  pacman:
    state: installed
    package:
    - htop
    - iotop
    - powertop
  become: yes

- name: install frequently used applications
  pacman:
    state: installed
    package:
    - gnu-netcat
    - wget
    - curl
    - mc
    - unzip
    - the_silver_searcher
    - dosfstools
    - bind-tools
    - ripgrep
    - sshfs
    - translate-shell
    - fd
    - bandwhich
  become: yes

- include: mpd.yml
