---
- name: configure trackpoint
  copy: src=templates/xorg/20-trackpoint.conf dest=/etc/X11/xorg.conf.d/20-trackpoint.conf
  become: yes
- name: disable trackpad
  copy: src=templates/xorg/20-trackpad.conf dest=/etc/X11/xorg.conf.d/20-trackpad.conf
  become: yes

- name: replace prtsc key with right meta
  copy: src=templates/hwdb/90-kbd-rmeta-insteadof-prtsc.hwdb dest=/etc/udev/hwdb.d/90-kbd-rmeta-insteadof-prtsc.hwdb
  become: yes
  register: hwdb_rightmeta
- name: increase trackpoint sensitivity
  copy: src=templates/udev/10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules
  become: yes
  register: rules_trackpoint
- name: update hwdb.bin
  command: udevadm hwdb --update
  become: yes
  when: hwdb_rightmeta.changed or rules_trackpoint.changed
- name: trigger udevadm
  command: udevadm trigger
  become: yes
  when: hwdb_rightmeta.changed or rules_trackpoint.changed

- name: install tlp
  pacman: package=tlp state=installed
  become: yes
- name: configure tlp
  copy: src=templates/tlp.conf dest=/etc/tlp.d/thinkpad.conf
  become: yes
- name: enable tlp
  systemd: name=tlp enabled=yes state=started
  become: yes
- name: disable systemd-rfkill as it conflicts with tlp
  systemd: name={{ item }} state=stopped enabled=no
  become: yes
  with_items:
  - systemd-rfkill.service
  - systemd-rfkill.socket
