- hosts: localhost
  tasks:
    - name: "desktop: install packages"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        # appearance
        - lxappearance
        - gnome-themes-standard
        - zukitwo-themes  # garage22
        # various software
        - libreoffice-still
        - libreoffice-still-be
        - libreoffice-still-ru
        - evince
        - gimp
        - sxiv
        - ntfsprogs
