- hosts: localhost
  tasks:
    - name: "desktop: install packages"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        # base X11 packages
        - xorg-server
        - xorg-server-xephyr
        - xorg-apps
        - xf86-video-intel
        # vital desktop stuff
        - awesome
        - vicious
        - sbxkb
        - i3lock
        - gnome-keyring
        # terminal
        - rxvt-unicode
        - urxvt-perls
        - the_silver_searcher
        # desktop manager
        - lightdm
        - lightdm-gtk3-greeter
        # appearance
        - lxappearance
        - gnome-themes-standard
        - zukitwo-themes  # garage22
        # various software
        - openssh
        - wget
        - gnu-netcat
        - emacs
        - firefox
        - chromium
        - luakit
        - flashplugin
        - thunderbird
        - unzip
        - libreoffice-calc
        - libreoffice-draw
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-writer
        - libreoffice-be
        - libreoffice-ru
        - evince
        - sxiv
        # sound
        - pulseaudio
        - pulseaudio-alsa
        - alsa-utils
        - pavucontrol
        - lib32-libpulse  # mostly for Skype
        - lib32-alsa-plugins  # mostly for Skype
        # deadbeef and optional dependencies
        - deadbeef
        - ffmpeg
        - libvorbis
        - libmad
        - flac
        # messaging
        - skype
        - psi
    - name: "desktop: set default pulseaudio sink"
      shell: pactl set-default-sink alsa_output.usb-GYROCOM_C_C_Co.__LTD_Audiotrak_ProDigy_CUBE-01-CUBE.analog-stereo
    - name: "desktop: install fonts"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - ttf-dejavu
        - ttf-bitstream-vera
        - ttf-inconsolata
        - ttf-ubuntu-font-family
        - terminus-font
        - ttf-ms-fonts  # garage22
    - name: "desktop: .Xprofile"
      copy: >
        src=../templates/home/user/.Xprofile
        dest=/home/{{ ansible_user_id }}/.Xprofile
    - name: "desktop: .icons"
      copy: >
        src=../templates/home/user/.icons/
        dest=/home/{{ ansible_user_id }}/.icons/
