- hosts: localhost
  tasks:
    - name: "developer: install Python and tools"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - python
        - python2
        - pypy
        - pypy3
        - ipython
        - ipython2
        - python-virtualenv
        - python2-virtualenv
        - python-virtualenvwrapper
        - python-virtualenv-clone
        - python2-virtualenv-clone
        - flake8
        - python2-flake8
    - name: "developer: install Rust tools"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - multirust
        - rust-racer
    - name: "developer: install debug tools"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - strace
        - ltrace
        - lsof
        - valgrind
