- hosts: localhost
  tasks:
    - name: "grub: copy hold_shift handler"
      copy: >
        src=../templates/etc/grub.d/31_hold_shift
        dest=/etc/grub.d/31_hold_shift
      sudo: yes
      notify:
      - generate grub config
  handlers:
    - name: "generate grub config"
      shell: grub-mkconfig -o /boot/grub/grub.cfg
      sudo: yes
