- hosts: localhost
  tasks:
    - name: "mail: install packages"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - offlineimap
        - mu-git
    - name: "mail: .offlineimaprc"
      copy: >
        src=../templates/home/user/.offlineimaprc
        dest=/home/{{ ansible_user_id }}/.offlineimaprc
    - name: "mail: offlineimap.py"
      copy: >
        src=../templates/home/user/mail/offlineimap.py
        dest=/home/{{ ansible_user_id }}/mail/offlineimap.py
    - name: "mail: Maildir gmail"
      file: >
        path=/home/{{ ansible_user_id }}/mail/gmail
        state=directory
        mode=0700
    - name: "mail: Maildir nottcc"
      file: >
        path=/home/{{ ansible_user_id }}/mail/nottcc
        state=directory
        mode=0700
    - name: "mail: offlineimap.service"
      copy: >
        src=../templates/home/user/.config/systemd/user/offlineimap.service
        dest=/home/{{ ansible_user_id }}/.config/systemd/user/offlineimap.service
    - name: "mail: offlineimap.timer"
      copy: >
        src=../templates/home/user/.config/systemd/user/offlineimap.timer
        dest=/home/{{ ansible_user_id }}/.config/systemd/user/offlineimap.timer

