- hosts: localhost
  tasks:
    - name: "system: install netctl and wireless tools"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - netctl
        - dialog  # used by wifi-menu
        - wpa_supplicant
        - wpa_actiond
        - wireless_tools
    - name: "system: install btrfs progs"
      pacman: name=btrfs-progs state=installed
      sudo: yes
    - name: "system: install ntp"
      pacman: name=ntp state=installed
      sudo: yes
    - name: "system: enable ntp"
      service: name=ntpd enabled=yes state=started
      sudo: yes
