- hosts: localhost
  tasks:
    - name: "system: install netctl and wireless tools"
      pacman: name={{ item }} state=installed
      sudo: yes
      with_items:
        - netctl
        - dialog  # used by wifi-menu
        - wpa_supplicant
        - wpa_actiond
        - wireless_tools
